name: Drupal Recipe Geo Images'
description: 'Enables advanced Geo Mapping functionalities with Media Images'
type: 'Geo Mapping'
install:
  - node
  - media
  - media_library_importer
  - media_image_exif_importer
  - geofield
  - leaflet_views
  - leaflet_markercluster
  - geocoder_geofield
config:
  import:
    media: '*'
